### ISSUE TITLE
koja verzija e funkcionalna 1.2 ili 1.3 ?

### ISSUE THREAD

**Issue by apopovski72** [mil-los/woocommerce-halk-bank-payment-gateway#1]
Zdravo, naidov na ovoj repository i na uste eden (mozebi e istiot no tamu bese 1.3 verzija) kade sto hashv3 e sredeno.  Od tuka koga go instalirav pluginot no gledam seuste javuva toa deka ne raboti posle april , pretpostavuvam deka e sredeno a ova  e samo ostanatat notifikacija.

Imam nekoj problem i probuvam da vidam do sto e. Na eden sajt so elementor raboti pluginot a na drug sajt pravi redirect vo urlto do halkbank stranata i odma potoa vraka nazad na checkout stranata. Probuvam da otkriajm  dali e problemot do pluginot do halkbanka  ili pak nesto na webstranata.

**Comment by mil-los** [comment]
Zdravo druze ova go pravev za drugrce sto ima sajt i znam deka kaj nego momentalno raboti vekje neklku meseci kje moram da proveram pa da ti kazam samo momentalno ne sum vo sostojba. S3 nadevam ne ti e za brzanje, kje te baram vo prva prilika, najverojatno negde posle 10ti. Pozdrav.

**Comment by mil-los** [comment]
Druze neznam sto uspea da napravis ako ti trebam nesto da ne se pisuvame tuka baraj me na 072 304 243.

**Comment by apopovski72** [comment]
Zdravo Druze,Fala ti mnogu .  Prorabote  ok e .  Mislam deka problem bese bekoj modprobe security block ili slicno zasto pluginot pravese reredirect  kako treba i odma instant se vrakase nazad od halkbanka portalot nazad na eeb stranata. Valjda posle x vreme 48h ilo 72h neznam prorabote.  Fala ti vo sekoj slucaj i jas  a prijateli sreduvam :).PozzzAleksandar
-------- Original message --------From: mil-los ***@***.***> Date: 10/11/24  13:11  (GMT+01:00) To: mil-los/woocommerce-halk-bank-payment-gateway ***@***.***> Cc: apopovski72 ***@***.***>, Author ***@***.***> Subject: Re: [mil-los/woocommerce-halk-bank-payment-gateway] koja verzija e funkcionalna 1.2 ili 1.3 ? (Issue #1) 
Druze neznam sto uspea da napravis ako ti trebam nesto da ne se pisuvame tuka baraj me na 072 304 243.
